SRCS_PATH= srcs/

all:
	clang++ -g -Wzero-as-null-pointer-constant main.cpp ${SRCS_PATH}Bureaucrat.cpp ${SRCS_PATH}Form.cpp ${SRCS_PATH}ShubberryCreationForm.cpp \
						${SRCS_PATH}PresidentialPardonForm.cpp ${SRCS_PATH}RobotomyRequestForm.cpp